import type { Metadata } from "next";
import Link from "next/link";
import { CtaSection } from "@/components/CtaSection";
import { Faq } from "@/components/Faq";
import { QrGenerator } from "@/components/QrGenerator";
import { Reveal, Stagger, StaggerItem } from "@/components/motion";
import { ArrowLink, Eyebrow, SectionHeading } from "@/components/ui";
import { site } from "@/data/site";
import { ogImage } from "@/lib/og";
import { breadcrumbSchema } from "@/lib/schema";

export const metadata: Metadata = {
  title: "Free QR Code Generator — WiFi, vCard, UPI, Logo — No Expiry",
  description:
    "QR codes that never expire: links, WiFi logins, contact cards, UPI payments and more — with your logo, custom colours, print-quality SVG. Free, in-browser.",
  keywords: [
    "qr code generator",
    "free qr code generator",
    "qr code generator no expiry",
    "qr code generator no sign up",
    "qr code svg download",
    "qr code for link",
    "permanent qr code",
  ],
  alternates: { canonical: "/qr-code-generator" },
  openGraph: {
    title: "Free QR Code Generator — No Signup, No Expiry, PNG & SVG",
    description:
      "QR codes that never expire. Print-quality SVG and PNG, no signup, no watermark, generated in your browser.",
    url: `${site.url}/qr-code-generator`,
    type: "website",
    images: ogImage("QR codes that never expire", "Free Generator"),
  },
};

const truths = [
  {
    title: "Static codes never expire",
    body: "The content is encoded in the pattern itself, like ink on paper. No account, no server, no renewal fee can take it away. Anyone telling you your QR code \"expires\" sold you a redirect, not a QR code.",
  },
  {
    title: "The \"free trial\" trap",
    body: "Many generators give you a dynamic code that routes through their server, then disable it when the trial ends — after you've printed it. Every code made here is yours, permanently.",
  },
  {
    title: "SVG is the print format",
    body: "A PNG has pixels; blow it up and it blurs. The SVG download is vector — sharp at business-card size and on a billboard alike. Most tools charge for it. Here it is free.",
  },
  {
    title: "Contrast is what scans",
    body: "Phone cameras want a dark pattern on a light background with quiet space around it. Fancy inverted or low-contrast codes look clever and scan badly.",
  },
];

const faqs = [
  {
    q: "Do these QR codes expire?",
    a: "No. These are static QR codes — the link or text is encoded directly in the pattern, so the code works forever, offline, with no account. It only stops working if the destination itself (your website) goes away.",
  },
  {
    q: "What is the difference between static and dynamic QR codes?",
    a: "A static code contains your link directly. A dynamic code contains a redirect through the provider's server, which lets them count scans and change the destination — and disable it when you stop paying. For printing a link that must simply keep working, static is the safer choice.",
  },
  {
    q: "Can I use these commercially?",
    a: "Yes — on menus, packaging, business cards, posters, vehicles, anywhere. There is no watermark, no attribution requirement and no license fee.",
  },
  {
    q: "PNG or SVG — which should I download?",
    a: "PNG for screens: websites, WhatsApp, presentations. SVG for anything printed: it scales to any size without blurring. When a print shop asks for \"vector\", the SVG is what they mean.",
  },
  {
    q: "Is my link or text stored anywhere?",
    a: "No. The code is generated by your own browser on this page. Nothing you type is sent to this server, logged or stored.",
  },
  {
    q: "How do I track scans then?",
    a: "Encode a link with a UTM parameter (like ?utm_source=qr) and read the visits in your analytics. You get scan counts without renting your QR code from anyone.",
  },
];

const toolSchema = {
  "@context": "https://schema.org",
  "@type": "WebApplication",
  name: "QR Code Generator",
  applicationCategory: "BusinessApplication",
  operatingSystem: "Any",
  url: `${site.url}/qr-code-generator`,
  description:
    "Free static QR code generator with PNG and print-quality SVG downloads. No signup, no expiry, no watermark; runs entirely in the browser.",
  provider: { "@id": `${site.url}/#studio` },
  offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
};

const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faqs.map((f) => ({
    "@type": "Question",
    name: f.q,
    acceptedAnswer: { "@type": "Answer", text: f.a },
  })),
};

export default function QrCodeGeneratorPage() {
  const crumbs = breadcrumbSchema([
    { name: "Free Tools", path: "/free-tools" },
    { name: "QR Code Generator", path: "/qr-code-generator" },
  ]);

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(toolSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(crumbs) }} />

      <section className="bg-noise relative overflow-hidden pt-36 pb-16 sm:pt-44">
        <div aria-hidden className="bg-grid absolute inset-0" />
        <div className="relative mx-auto max-w-6xl px-5 sm:px-8">
          <div className="flex flex-col items-center gap-6 text-center">
            <Eyebrow>Free QR Generator</Eyebrow>
            <h1 className="text-balance text-4xl sm:text-6xl">
              QR codes that <span className="text-gradient">never expire</span>.
            </h1>
            <p className="max-w-2xl text-pretty text-lg leading-relaxed text-muted">
              Links, Wi-Fi logins, contact cards, UPI payments and WhatsApp
              chats — with your logo in the centre and print-quality SVG. No
              signup, no watermark, no &ldquo;your code has been
              deactivated&rdquo; email after you&apos;ve printed five hundred
              menus.
            </p>
          </div>
          <div className="mt-14">
            <QrGenerator />
          </div>
        </div>
      </section>

      <section className="border-t border-line">
        <div className="mx-auto max-w-6xl px-5 py-20 sm:px-8">
          <Reveal>
            <SectionHeading
              eyebrow="Worth knowing"
              title="The honest facts about QR codes."
            />
          </Reveal>
          <Stagger className="mt-12 grid gap-px border border-line bg-line sm:grid-cols-2">
            {truths.map((t) => (
              <StaggerItem key={t.title} className="bg-background">
                <div className="flex h-full flex-col gap-3 p-7">
 <h3 className="font-display text-xl leading-none">{t.title}</h3>
                  <p className="text-sm leading-relaxed text-muted">{t.body}</p>
                </div>
              </StaggerItem>
            ))}
          </Stagger>
          <Reveal className="mt-10">
            <p className="text-sm leading-relaxed text-muted">
              Pointing the code at your website? Make sure the page holds up
              when they arrive —{" "}
              <Link href="/free-website-audit" className="u-draw text-accent">
                run the free audit
              </Link>{" "}
              or pair it with the{" "}
              <Link href="/whatsapp-link-generator" className="u-draw text-accent">
                WhatsApp link generator
              </Link>
              .
            </p>
          </Reveal>
        </div>
      </section>

      <section className="border-t border-line">
        <div className="mx-auto max-w-3xl px-5 py-20 sm:px-8">
          <Reveal>
            <SectionHeading eyebrow="FAQ" title="Fair questions." align="center" />
          </Reveal>
          <div className="mt-10">
            <Faq items={faqs} />
          </div>
          <div className="mt-12 text-center">
            <ArrowLink href="/free-tools">Explore all free tools</ArrowLink>
          </div>
        </div>
      </section>

      <CtaSection />
    </>
  );
}
